"""Changed transaction_id on Payment model type to UUID

Revision ID: e6e2f031118a
Revises: 27093299c4d3
Create Date: 2026-04-10 20:50:25.994195

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6e2f031118a"
down_revision: Union[str, Sequence[str], None] = "27093299c4d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment", schema=None) as batch_op:
        batch_op.alter_column(
            "transaction_id",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.Uuid(),
            existing_nullable=False,
            postgresql_using="transaction_id::uuid",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment", schema=None) as batch_op:
        batch_op.alter_column(
            "transaction_id",
            existing_type=sa.Uuid(),
            type_=sa.VARCHAR(length=255),
            existing_nullable=False,
            postgresql_using="transaction_id::text",
        )

    # ### end Alembic commands ###
